/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import model from "../../assets/threejs/Black.glb";
import model2 from "../../assets/threejs/White.glb";
const Mesh = (props) => {
  const { nodes, materials } = useGLTF(model);
  const { nodes: one, materials: materials1 } = useGLTF(model2);
  const mainRef = useRef(null);
  const baseRef = useRef(null);

  useEffect(() => {
    // console.log(two, ' base');
  }, []);
  // sole
  // stripe
  // back
  // top
  console.log(mainRef);
  return (
    <mesh {...props} dispose={null} ref={mainRef} position={[0, 0, 0]}>
      <mesh
        receiveShadow
        geometry={nodes.Backfoam.geometry}
        material={props.back ? materials1.ASSET_MAT_MR : materials.ASSET_MAT_MR}

      />
      <mesh
        receiveShadow
        geometry={nodes.Strip.geometry}
        material={
          props.stripe ? materials1.ASSET_MAT_MR : materials.ASSET_MAT_MR
        }

      />
      <mesh
        receiveShadow
        geometry={nodes.MainBody.geometry}
        material={props.top ? materials1.ASSET_MAT_MR : materials.ASSET_MAT_MR}
      />
      <mesh
        receiveShadow
        geometry={nodes.Sole.geometry}
        material={props.sole ? materials1.ASSET_MAT_MR : materials.ASSET_MAT_MR}
        castShadow
        ref={baseRef}
        onClick={() => console.log("ok")}
      />
    </mesh>
  );
};

export default Mesh;
